#!/bin/bash
# AtonixCorp Hardware Detection Script
# Detects and configures hardware security features

set -e

LOG_FILE="/var/log/atonix-hardware-detect.log"
CONFIG_FILE="/etc/atonix/atonix-hardware.conf"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $*" >> "$LOG_FILE"
    echo "$*"
}

detect_tpm() {
    log "Detecting TPM devices..."

    if [ -c /dev/tpm0 ]; then
        log "TPM 1.2 device found at /dev/tpm0"
        echo "TPM12_ENABLED=1" >> "$CONFIG_FILE"
    fi

    if [ -c /dev/tpmrm0 ]; then
        log "TPM 2.0 device found at /dev/tpmrm0"
        echo "TPM20_ENABLED=1" >> "$CONFIG_FILE"
    fi

    # Check for TPM modules
    if lsmod | grep -q tpm; then
        log "TPM kernel modules loaded"
        echo "TPM_MODULES_LOADED=1" >> "$CONFIG_FILE"
    fi
}

detect_sgx() {
    log "Detecting Intel SGX..."

    if [ -d /dev/sgx_enclave ]; then
        log "Intel SGX enclave device found"
        echo "SGX_ENABLED=1" >> "$CONFIG_FILE"
    fi

    if [ -c /dev/sgx_enclave ]; then
        log "Intel SGX enclave character device found"
        echo "SGX_CHARDEV_ENABLED=1" >> "$CONFIG_FILE"
    fi

    # Check CPU capabilities
    if grep -q sgx /proc/cpuinfo; then
        log "CPU supports SGX"
        echo "SGX_CPU_SUPPORTED=1" >> "$CONFIG_FILE"
    fi
}

detect_sev() {
    log "Detecting AMD SEV..."

    if grep -q sev /proc/cpuinfo; then
        log "AMD SEV supported by CPU"
        echo "SEV_ENABLED=1" >> "$CONFIG_FILE"
    fi

    if [ -c /dev/sev ]; then
        log "AMD SEV device found"
        echo "SEV_DEVICE_ENABLED=1" >> "$CONFIG_FILE"
    fi
}

detect_optee() {
    log "Detecting OP-TEE..."

    if [ -c /dev/tee0 ]; then
        log "OP-TEE device found at /dev/tee0"
        echo "OPTEE_ENABLED=1" >> "$CONFIG_FILE"
    fi

    if [ -d /lib/optee_armtz ]; then
        log "OP-TEE Trusted Applications directory found"
        echo "OPTEE_TA_ENABLED=1" >> "$CONFIG_FILE"
    fi
}

detect_trustzone() {
    log "Detecting ARM TrustZone..."

    if [ -c /dev/trustzone ]; then
        log "ARM TrustZone device found"
        echo "TRUSTZONE_ENABLED=1" >> "$CONFIG_FILE"
    fi

    # Check for secure world indicators
    if [ -d /sys/firmware/secure_world ]; then
        log "Secure world firmware detected"
        echo "SECURE_WORLD_ENABLED=1" >> "$CONFIG_FILE"
    fi
}

main() {
    log "Starting AtonixCorp hardware detection..."

    # Create config directory if it doesn't exist
    mkdir -p "$(dirname "$CONFIG_FILE")"

    # Initialize config file
    echo "# AtonixCorp Hardware Configuration" > "$CONFIG_FILE"
    echo "# Auto-generated by hardware detection script" >> "$CONFIG_FILE"
    echo "DETECTION_DATE=$(date)" >> "$CONFIG_FILE"

    # Detect hardware features
    detect_tpm
    detect_sgx
    detect_sev
    detect_optee
    detect_trustzone

    # Set overall hardware security status
    if grep -q "ENABLED=1" "$CONFIG_FILE"; then
        echo "HARDWARE_SECURITY_ENABLED=1" >> "$CONFIG_FILE"
        log "Hardware security features detected and enabled"
    else
        echo "HARDWARE_SECURITY_ENABLED=0" >> "$CONFIG_FILE"
        log "No hardware security features detected"
    fi

    log "Hardware detection completed"
}

main "$@"
