# Generated by Django 5.2.6 on 2025-10-09 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_user_role',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='access_cont_user_id_f41890_idx',
            old_name='access_control_auditlog_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='access_cont_action_9a2e1d_idx',
            old_name='access_control_auditlog_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='access_cont_ip_addr_987bec_idx',
            old_name='access_control_auditlog_ip_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='access_cont_created_39d44f_idx',
            old_name='access_control_auditlog_created_at_idx',
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('user', 'role')},
        ),
    ]
