source 'https://rubygems.org'

ruby '3.2.0'

# Web server
gem 'puma', '~> 6.4'

# Background job processing
gem 'sidekiq', '~> 7.2'
gem 'sidekiq-scheduler', '~> 5.0'

# Web framework
gem 'sinatra', '~> 3.1'
gem 'sinatra-contrib', '~> 3.1'

# Database
gem 'pg', '~> 1.5'
gem 'redis', '~> 5.0'
gem 'sequel', '~> 5.70'

# Distributed coordination
gem 'zookeeper', '~> 1.5'

# API and serialization
gem 'grape', '~> 2.0'
gem 'grape-entity', '~> 1.0'
gem 'json', '~> 2.6'

# HTTP client
gem 'faraday', '~> 2.7'
gem 'faraday-multipart', '~> 1.0'

# Configuration
gem 'dotenv', '~> 2.8'

# Logging
gem 'semantic_logger', '~> 4.12'

# Monitoring
gem 'prometheus-client', '~> 4.2'

# Security
gem 'rack-protection', '~> 3.1'
gem 'bcrypt', '~> 3.1'

# Development and testing
group :development do
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
  gem 'rerun', '~> 0.14'
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-performance', '~> 1.19'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'webmock', '~> 3.18'
  gem 'vcr', '~> 6.1'
  gem 'database_cleaner-sequel', '~> 2.0'
end

# Deployment
gem 'capistrano', '~> 3.17', group: :development