# Generated by Django 4.2.25 on 2025-11-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='An IP address or CIDR range, e.g. 1.2.3.4 or 203.0.113.0/24', max_length=64, unique=True)),
                ('is_cidr', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blocked IP / Network',
                'verbose_name_plural': 'Blocked IPs & Networks',
            },
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
