---
# Knative Service — Standard function deployment template
# Usage: copy and modify for each function
#
# kubectl apply -f serverless/functions/templates/knative-service.yaml -n <team-namespace>

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-function                        # ← change per function
  namespace: team-default                  # ← change per team
  labels:
    app: my-function
    team: platform                         # ← change per team
    ax/tier: serverless
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "20"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "50"
        # Prometheus metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      # Service account for this function (scoped credentials via identity/)
      serviceAccountName: function-sa      # ← matches identity/rbac/ service account
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: ghcr.io/atonixcorp/my-function:latest   # ← change per function
          ports:
            - name: h2c
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: LOG_LEVEL
              value: "info"
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          # Readiness probe
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
